module MuseekBindings::Message
  autoload :Base, 'museek_bindings/message/base'
  autoload :Transfer, 'museek_bindings/message/transfer'
  autoload :TransferAbort, 'museek_bindings/message/transfer_abort'
  autoload :DownloadFolder, 'museek_bindings/message/download_folder'
  autoload :DownloadFile, 'museek_bindings/message/download_file'
  autoload :Challenge, 'museek_bindings/message/challenge'
  autoload :Login, 'museek_bindings/message/login'
  autoload :ServerState, 'museek_bindings/message/server_state'
  autoload :PrivateMessage, 'museek_bindings/message/private_message'
  autoload :RoomList, 'museek_bindings/message/room_list'
  autoload :JoinRoom, 'museek_bindings/message/join_room'
  autoload :LeaveRoom, 'museek_bindings/message/leave_room'
  autoload :SayRoom, 'museek_bindings/message/say_room'
  autoload :UserInfo, 'museek_bindings/message/user_info'
  autoload :UserShares, 'museek_bindings/message/user_shares'
  autoload :PeerStats, 'museek_bindings/message/peer_stats'
  autoload :Search, 'museek_bindings/message/search'
  autoload :SearchReply, 'museek_bindings/message/search_reply'
  autoload :ReloadShares, 'museek_bindings/message/reload_shares'
end
